import type { RawMixin } from "./types";

const pascal = (s: string): string =>
  s.replace(/(^|[-_ ])(\w)/g, (_m, _p, c: string) => c.toUpperCase());
const kebab = (s: string): string =>
  s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/[_ ]+/g, "-").toLowerCase();
/** A valid TS identifier base — schema keys can be ids (`68e2…`) that aren't valid identifiers. */
const safeName = (s: string): string => {
  const p = pascal(s).replace(/[^A-Za-z0-9]/g, "");
  return /^[A-Za-z]/.test(p) ? p : `Mixin${p}`;
};
const typeName = (m: RawMixin): string => `${safeName(m.key)}MixinV${m.version}`;

const BANNER = "// AUTO-GENERATED by @viu/emporix-mixins — do not edit.\n";

/** Generates `{ "<kebab>.ts": <interface>, "registry.ts": <registry> }` from raw mixins. */
export async function generateTypes(raw: RawMixin[]): Promise<Record<string, string>> {
  const { compile } = await import("json-schema-to-typescript");
  const files: Record<string, string> = {};
  const imports: string[] = [];
  const entries: string[] = [];
  for (const m of raw) {
    const ts = await compile(m.schema as never, typeName(m), {
      bannerComment: "",
      additionalProperties: false,
    });
    // json-schema-to-typescript re-normalizes the requested name (e.g. inserts
    // case at digit boundaries), so reference the name it ACTUALLY emitted.
    const name = ts.match(/export (?:interface|type)\s+(\w+)/)?.[1] ?? typeName(m);
    const file = `${kebab(m.key)}.ts`;
    files[file] = BANNER + ts;
    imports.push(`import type { ${name} } from "./${kebab(m.key)}";`);
    entries.push(
      `  ${JSON.stringify(m.key)}: { key: ${JSON.stringify(m.key)}, entity: ${JSON.stringify(m.entity)}, ` +
        `version: ${m.version}, url: ${JSON.stringify(m.url)}, schema: ${JSON.stringify(m.schema)} } as MixinDescriptor<${name}>,`,
    );
  }
  files["registry.ts"] =
    BANNER +
    `import type { MixinDescriptor } from "@viu/emporix-mixins";\n` +
    imports.join("\n") +
    `\n\nexport const mixins = {\n${entries.join("\n")}\n} as const;\n`;
  return files;
}
