openapi: 3.0.0
info:
  title: Customer Service (tenant-managed)
  version: ''
  description: |-
    Create, manage, and delete customer profiles.
  contact:
    name: Emporix
    url: 'https://emporix.com'
    email: documentation@emporix.com
servers:
  - url: 'https://api.emporix.io'
tags:
  - name: Account and profile
  - name: Addresses
  # - name: Assisted buying login
paths:
  '/customer/{tenant}/customers':
    get:
      summary: Retrieving a list of customers
      description: |-
        Retrieves a list of customer profiles.
      operationId: GET-customer-tenant-list-customers
      security:
        - OAuth2:
            - customer.customer_read
            - customer.customer_read_own
      tags:
        - Account and profile
    post:
      summary: Creating a customer
      description: |-
        Creates a new customer.
      operationId: POST-customer-tenant-create-customer
      security:
        - OAuth2:
            - customer.customer_manage
            - customer.customer_manage_own
      tags:
        - Account and profile
  '/customer/{tenant}/customers/search':
    post:
      summary: Searching for customers
      description: |-
        Searches for customer profiles.
      operationId: POST-customer-tenant-search
      security:
        - OAuth2:
            - customer.customer_read
            - customer.customer_read_own
      tags:
        - Account and profile
  '/customer/{tenant}/customers/{customerNumber}':
    put:
      summary: Upserting a customer profile
      description: |
        Updates a specified customer profile or creates a new one if it doesn't exist yet.
      operationId: PUT-customer-tenant-update-customer
      security:
        - OAuth2:
            - customer.customer_manage
            - customer.customer_manage_own
      tags:
        - Account and profile
    patch:
      summary: Updating a customer profile
      description: |
        Updates a specified customer profile.
      operationId: PATCH-customer-tenant-update-customer
      security:
        - OAuth2:
            - customer.customer_manage
            - customer.customer_manage_own
      tags:
        - Account and profile
    get:
      summary: Retrieving a customer profile
      description: |-
        Retrieves a specified customer profile.
      operationId: GET-customer-tenant-retrieve-customer
      security:
        - OAuth2:
            - customer.customer_read
            - customer.customer_read_own
      tags:
        - Account and profile
    delete:
      summary: Deleting a customer profile
      description: |
        Deletes a specified customer profile and accounts associated with it.     
      operationId: DELETE-customer-tenant-remove-customer
      security:
        - OAuth2:
            - customer.customer_manage
            - customer.customer_manage_own
      tags:
        - Account and profile
  '/customer/{tenant}/customers/{customerNumber}/addresses':
    get:
      summary: Retrieving customer addresses
      description: |-
        Retrieves a list of addresses for a specified customer.
      operationId: GET-customer-tenant-list-customer-addresses
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_read
    post:
      summary: Adding a customer address
      description: |
        Adds an address to a specified customer profile.
      operationId: POST-customer-tenant-add-customer-address
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_manage
  '/customer/{tenant}/customers/{customerNumber}/addresses/{addressId}':
    put:
      summary: Upserting a customer address
      description: |
        Updates a specified customer address or creates a new one if it doesn't exist yet.
      operationId: PUT-customer-tenant-update-customer-address
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_manage
    patch:
      summary: Partially updating a customer address
      description: |
        Updates a specified customer address.
      operationId: PATCH-customer-tenant-update-customer-address
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_manage
    get:
      summary: Retrieving a customer address
      description: |
        Retrieves a specified customer address and its details.
      operationId: GET-customer-tenant-retrieve-customer-address-by-id
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_read
    delete:
      summary: Deleting a customer address
      description: |
        Deletes a specified customer address.
      operationId: DELETE-customer-tenant-remove-customer-address
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_manage
  '/customer/{tenant}/customers/{customerNumber}/addresses/{addressId}/tags':
    post:
      summary: Adding tags to a customer address
      description: |
        Adds tags to a specified customer address.
      operationId: POST-customer-tenant-add-address-tags
      tags:
        - Addresses
    delete:
      summary: Deleting tags from a customer address
      description: |
        Deletes tags from a specified customer address.
      operationId: DELETE-customer-tenant-remove-address-tags
      tags:
        - Addresses
      security:
        - OAuth2:
            - customer.customer_manage
  # Hiding the assisted-buying endpoint as it's used only internally
  # '/customer/{tenant}/assisted-buying-login':
  #   parameters:
  #     - schema:
  #         type: string
  #       name: tenant
  #       in: path
  #       required: true
  #   post:
  #     summary: Generating a customer token
  #     operationId: POST-customer-tenant-assisted-buying-login
  #     responses:
  #       '200':
  #         $ref: '#/components/responses/AssistedBuyingLogin'
  #       '400':
  #         $ref: '#/components/responses/400_bad_request'
  #       '401':
  #         $ref: '#/components/responses/401_unauthorized'
  #       '403':
  #         $ref: '#/components/responses/403_forbidden'
  #     tags:
  #       - Assisted buying login
  #     description: |-
  #       The login feature is crucial for assistant buying functionality whenever a customer token has to be generated by an employee.

  #       **Required scopes**
  #       * `customer.assistedBuying_manage`

  #       **Note**: Please note that the `employee token` is required to complete this request to assure that an authorized person logs in as a customer. The endpoint doesn't work with API key.
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/AssistedBuyingLoginDto'
  #           examples:
  #             Assistant Login:
  #               value:
  #                 customerNumber: C412344
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          refreshUrl: ''
          scopes:
            customer.customer_read: Needed to retrieve customer profiles.
            customer.customer_read_own: Needed by customer to retrieve customer profiles from the same company.
            customer.customer_manage: Needed to manage customer profiles.
            customer.customer_manage_own: Needed by customer to manage customer profiles from the same company.
          tokenUrl: 'https://api.emporix.io/oauth/token'
security:
  - OAuth2: []